### ISSUE TITLE
HL processing crashes

### ISSUE THREAD

**Issue by zmolikova** [claritychallenge/clarity_CEC1#1]
Hi,
I ran into an issue when running `predict.sh`. Script `run_HL_processing.py` first gives a warning
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```
and then crashes with
```
Traceback (most recent call last):
  File "clarity_CEC1/scripts/../scripts/run_HL_processing.py", line 112, in <module>
    run_HL_processing(
  File "clarity_CEC1/scripts/../scripts/run_HL_processing.py", line 89, in run_HL_processing
    write_signal(filename, signal, CONFIG.fs, floating_point=True)
  File "clarity_CEC1/lib/clarity_core/clarity_core/signal.py", line 79, in write_signal
    soundfile.write(filename, x, fs, subtype=subtype)
  File "clarity_CEC1/env/lib/python3.8/site-packages/soundfile.py", line 316, in write
    f.write(data)
  File "clarity_CEC1/env/lib/python3.8/site-packages/soundfile.py", line 992, in write
    written = self._array_io('write', data, len(data))
  File "clarity_CEC1/env/lib/python3.8/site-packages/soundfile.py", line 1309, in _array_io
    ctype = self._check_dtype(array.dtype.name)
  File "clarity_CEC1/env/lib/python3.8/site-packages/soundfile.py", line 1298, in _check_dtype
    raise ValueError("dtype must be one of {0!r} and not {1!r}".format(
ValueError: dtype must be one of ['float32', 'float64', 'int16', 'int32'] and not 'object'
```

This happens on scene S06038, listener L0100 (before, it processes 36 other scenes without problems). After some debugging, I think that the problem happens in the simulation of the cochlea, where smearing is applied. The smearing changes the length of the signal  https://github.com/claritychallenge/clarity_CEC1/blob/f4af0f7113ed87fb18a1a71b31c2367be9e5d198/projects/MSBG/MSBG/cochlea.py#L248 which becomes a problem when it is applied on one ear only. This happens when one ear only has severity=NOTHING.  Then `outputs`  are not of the same length and the creation of the numpy array gives the warning. https://github.com/claritychallenge/clarity_CEC1/blob/f4af0f7113ed87fb18a1a71b31c2367be9e5d198/scripts/run_HL_processing.py#L25

**Comment by sgraetzer** [comment]
Dear zmolikova,
I came across the issue earlier today and am looking into it.
Many thanks for reporting it,
Simone

**Comment by sgraetzer** [comment]
We've just issued a fix. Thanks.

Note, if you have already installed the code you should be able to update it safely in-place with 'git pull'.  

You may get a warning about git not wanting to delete some local files, if so then please just delete these manually with

rm -rf data_test/clarity_data/dev/scenes
rm -rf data_test/clarity_data/train/scenes

and then try 'git pull' again.
