### ISSUE TITLE
Bug Fix: mbstoi.py

### ISSUE THREAD

**Issue by Thundor404** [claritychallenge/clarity_CEC1#3]
In MBSTOI calculation py script, see [here](https://github.com/claritychallenge/clarity_CEC1/blob/cbf3a7e91b7cbdf4d28e1e78061248c7a076966c/projects/MBSTOI/MBSTOI/mbstoi.py#L87)
There should be 
`abs(np.log10(np.linalg.norm(xl) / np.linalg.norm(yl))) > 5.0`
rather than
`abs(np.log10(np.linalg.norm(xl) / np.linalg.norm(xl))) > 5.0`

**Comment by sgraetzer** [comment]
Thundor404 thanks so much for alerting us to this bug! It wasn't caught with our unit tests. We'll fix this in the next release.
