### ISSUE TITLE
Baseline SII

### ISSUE THREAD

**Issue by zmolikova** [claritychallenge/clarity_CEC1#4]
Hi,
I think that the file with baseline intelligibility results was not updated after the last fix of the references. I am currently getting an average MBSTOI of about 0.53 while the `scripts/baseline_sii.txt` average is about 0.37. Is that correct?
Thank you!

**Comment by sgraetzer** [comment]
Hello Katerina,
Yes that is correct. We expect to release revised baseline scores soon.
Many thanks,
Simone
