### ISSUE TITLE
How to download data? 

### ISSUE THREAD

**Issue by oplatek** [claritychallenge/clarity_CEC1#6]
Hi!

I am interested in looking into the clarity evaluation from a dialogue TTS perspective for my thesis.
I would like to replicate the baseline implementation.
However, I have trouble finding how to obtain the data.

I checked:
- https://claritychallenge.github.io/clarity_CEC1_doc/docs/cec1_download
- https://github.com/claritychallenge/clarity_CEC1/blob/master/install/unpack.sh#L5

I did not find instructions on how to obtain the speech audio recordings.

I hope I did not miss something obvious.

Thank you for your help

Ondra

**Comment by sgraetzer** [comment]
Hello Ondra,

In the INSTALL.md file there is a link to the main download site where you will find all of the data necessary: https://www.myairbridge.com/en/#!/folder/iAvNdeGHtgE46bzB4o1KpRwJf0Lsphut

Please let me know if you would like further assistance or I can close this issue.

Kind regards,
Simone

**Comment by oplatek** [comment]
Thank you Simone! 

Sorry, I missed the link in the INSTALL.md it seems it is working fine
