### ISSUE TITLE
Last level on mild hearing loss audiogram looks off in audiogram.py

### ISSUE THREAD

**Issue by kdonbekci** [claritychallenge/clarity_CEC1#7]
At this line,

https://github.com/claritychallenge/clarity_CEC1/blob/e1ee4af568e0bd4c630b77d89a7a3cb981eea964/projects/MSBG/MSBG/audiogram.py#L37

the last hearing loss level is set to 5dbHL, but probably was meant to be 50?

**Comment by sgraetzer** [comment]
Hello kdonbekci,

Thanks for spotting this error, which we'll correct ASAP. The baseline system for CEC1 doesn't access this default set of values.

Simone
